# eureka_server 配置文件

server:
  port: 10080

spring:
  application:
    name: eurekaserver

# eureka相关配置
eureka:
  client:
    # 自己本身也是，使用要配置
    service-url:
      defaultZone: http://127.0.0.1:10080/eureka/



# 设置日志级别，root表示根节点，即整体应用日志级别
logging:
  # 日志输出到文件的文件名
  file:
    name: eureka_server.log
  # 设置日志组
  group:
    # 自定义组名，设置当前组中所包含的包
    mao_pro: mao
  level:
    root: info
    # 为对应组设置日志级别
    mao_pro: debug
    # 日志输出格式
  # pattern:
  # console: "%d %clr(%p) --- [%16t] %clr(%-40.40c){cyan} : %m %n"
