# order 业务 配置文件

spring:


  # 配置数据源
  datasource:

    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/cloud_order
      username: root
      password: 20010713




  application:
    name: orderservice

#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10080/eureka/


  cloud:
    nacos:
      discovery:
        # nacos 服务端地址
        server-addr: localhost:8848
        # 配置集群名称，也就是机房位置
        cluster-name: HZ
        # namespace: 5544c4b1-2899-4915-94af-f9940c01c2b9
        # 是否为临时实例，true为临时实例
        ephemeral: false

# 负载均衡
#userservice:
#  ribbon:
#    # 负载均衡规则
#    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule



# 开启debug模式，输出调试信息，常用于检查系统运行状况
#debug: true

# 设置日志级别，root表示根节点，即整体应用日志级别
logging:
 # 日志输出到文件的文件名
  file:
     name: order_server.log
  # 设置日志组
  group:
  # 自定义组名，设置当前组中所包含的包
    mao_pro: mao
  level:
    root: info
    # 为对应组设置日志级别
    mao_pro: debug
    # 日志输出格式
# pattern:
  # console: "%d %clr(%p) --- [%16t] %clr(%-40.40c){cyan} : %m %n"


# 配置负载均衡规则
#userservice:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule


ribbon:
  eager-load:
    # 开启饥饿加载
    enabled: true
    # 指定对 userservice 这个服务饥饿加载
    clients: userservice


server:
  port: 8081


mybatis:
  type-aliases-package: mao.order_service
  configuration:
    map-underscore-to-camel-case: true
